#version: '3.8'

services:
  php:
    build: .
    container_name: weather_forecast
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"


  nginx:
    image: nginx:latest
    container_name: weather_forecast_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php_fpm_exporter:
    image: hipages/php-fpm_exporter:latest
    container_name: php_fpm_exporter
    ports:
      - "9253:9253"
    environment:
      - PHP_FPM_SCRAPE_URI=http://php:9000/status

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri http://nginx:80/stub_status

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data: