global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'php'
    static_configs:
      - targets: ['php:9000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
